### ISSUE TITLE
problems when using sqlite3 with large profiled samples and deprecation warning

### ISSUE THREAD

**Issue by JoeyHendricks** [JoeyHendricks/QuickPotato#11]
Got the following error in one of my project will fix this and update QuickPotato.

```
C:\Program Files\Python38\lib\copyreg.py:91: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  return cls.__new__(cls, *args)


Ran 1 test in 1.273s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\My Documents\PycharmProject\venster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\OneDrive \My Documents\PycharmProject\venster\venv\lib\site-packages\sqlalchemy\engine\default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:
```

**Comment by JoeyHendricks** [comment]
problem is with amount of variables it is still sending to many variables, I am working on a work around for this.
